import LocalizedStrings from "react-native-localization";

const strings = new LocalizedStrings({
    en: {
        isRtl: false,
        hi: "Hi,",
        guest: "Guest",
        customers: "Customers",
        currency: "Currency",
        uploadData: "Upload Data",
        addCustomer: "Add Customer",
        firstName: "First Name",
        lastName: "Last Name",
        phone: "Phone",
        email: "Email",
        addCustomer: "Add Customer",
        cashBook: "Cash Book",
        show: "Show",
        cashIn: "Cash In",
        cash: "Cash",
        cashOut: "Cash Out",
        dateTime: "Date Time",
        date: "Date",
        prev: "Prev",
        next: "Next",
        noDataAvailable: "No Data Available",
        customer: "Customer",
        search: "Search",
        customerNotFound: "Customer Not Found",
        yourDataWillBeAutomatically: "Your data will be automatically deleted from the app 24 hours after using a guest account",
        update: "Update",
        founder: "Founder: Mohammad Nasar Yousafi",
        selfCash: "Self Cash",
        add: "Add",
        edit: "Edit",
        amount: "Amount",
        profit: "Profit",
        information: "Information",
        submit: "Submit",
        from: "From",
        to: "To",
        share: "Share",
        currency: "Currency",
        byChangingTheCurrency: "By changing the currency all data well change to that currency!",
        register: "Register",
        welcomeToBrainbbox: "Welcome To Brainbbox",
        loginWithGuest: "Login With Guest",
        loginWithGoogle: "Login With Google",
        privacyPolicy: "Privacy Policy",
        welcomeToLogin: "Welcome To Login",
        protectYourData: "Protect your data please use local authentication",
        biometricLogin: "Biometric Login",
        alert: "Alert",
        ok: "Ok",
        youEnteredInvalidTicket: "You Entered Invalid Ticket",
        noDataFound: "No Data Found",
        noContactFound: "No Contact Found",
        checkYourTicketHere: "Check Your Ticket Here",
        checkYourTicket: "Check Your Ticket",
        check: "Check",
        transactionInfo: "Transaction Info",
        owner: "Owner",
        name: "Name",
        type: "Type",
        info: "Info",
        dismiss: "Dismiss",
        profile: "Profile",
        general: "General",
        report: "Report",
        dailyReport: "Daily Report",
        balanceSheet: "Balance sheet",
        language: "Language",
        transactionInfo: "Transaction Info:",
        opposite: "Opposite",
        doyYouWantToDeleteTransaction: "Are you sure you want to delete this transaction? This action will impact your cashbook entries.",
        pleaseSelectCustomer: "Please select a customer!",
        heDontHaveEnoughCash: "He don't have enough cash to transper do you want debt?",
        balanceSheetCurrency: "Balance sheet currency",
        appLock: "App Lock",
        updateAvailable: "Update Available",
        newVersion: "A new version of the app is available. Please update for the best experience.",
        later: "Later",
        updateNow: "Update Now",
        runningBalance: "Running Balance",
        delete: "Delete",
        cancel: "Cancel",
        appBackup: "App Backup",
        PickdateToCreateYourAppBackup: "Pick a date to create your app backup.",
        yourAppBackupWillStore: "Your app backup will store in your device 'Download/brainbbox'.",
        backupCompleted: "Backup completed successfully",
        CashInSuccessfullyAdded: "Cash In successfully added.",
        CashOutSuccessfullyAdded: "Cash Out successfully added",
        pleaseEnterNumber: "Please Enter Number",
        pleaseTryAgain: "Please Try Again!",
        transper: "Transper",
        backup: "Backup",
        currencyRate: "Currency Rate",
        kabul: "Kabul",
        kandahar: "Kandahar",
        herat: "Herat",
        mazar_i_Sharif: "Mazar-i-Sharif",
        jalalabad: "Jalalabad",
        buy: "Buy",
        sell: "Sell",
        currencyConverter: "Currency Converter",
        fromCurrency: "From Currency",
        toCurrency: "To Currency",
        justnow: "Just now",
        minute: "minute",
        ago: "ago",
        hour: "hour",
        day: "day",
        reminder: "Reminder",
        paymentReminder: "Payment Reminder",
        remindeBy: "Reminde By",
        noCurrencyRateFound: "No Currency Rate Found",
        done: "Done",
        deleteAccount: "Delete Account",
        MayWeAskWhy: "May we ask why you're leaving?",
        send: "Send",
        areYouSureToDeleteAccount: "Are you sure you want to delete your account?",
        sure: "Sure",
        deleteAccountMessage: "Your account will be deleted in 24 hourse.",
        success: "Success",
        customerSuccessfullyAdded: "Customer successfully added",
        profileSuccessfullyChanged: "Profile successfully changed",
        privacyPolicy: "Privacy Policy",
        privacyPolicyMessage: "By using this app, you agree to our Privacy Policy and Terms of Service.",
        agree: "Agree",
        disagree: "Disagree",
    },
    ps: {
        isRtl: true,
        hi: "سلام،",
        guest: "میلمه",
        customers: "پیرودونکي",
        currency: "اسعار",
        uploadData: "ډاټا پورته کړئ",
        addCustomer: "پیرودونکی اضافه کړئ",
        firstName: "لومړی نوم",
        lastName: "تخلص",
        phone: "ټیلیفون",
        email: "بریښنالیک",
        cashBook: "نغدي کتاب",
        show: "ښودل",
        cashIn: "نغدي دننه",
        cash: "نغدي",
        cashOut: "نغدي بهر",
        dateTime: "نېټه او وخت",
        date: "نېټه",
        prev: "مخکینی",
        next: "بل",
        noDataAvailable: "هیڅ معلومات موجود نه دي",
        customer: "پیرودونکی",
        search: "لټون",
        customerNotFound: "پیرودونکی ونه موندل شو",
        yourDataWillBeAutomatically: "ستاسو ډاټا به په اوتومات ډول د میلمه حساب کارولو څخه ۲۴ ساعتونو وروسته له اپلیکیشن څخه پاک شي",
        update: "تازه کول",
        founder: "بنسټګر: محمد ناصر یوسفي",
        selfCash: "خپله نغدي",
        add: "اضافه کول",
        edit: "سمول",
        amount: "مقدار",
        profit: "ګټه",
        information: "معلومات",
        submit: "سپارل",
        from: "له",
        to: "ته",
        share: "شریکول",
        currency: "اسعار",
        byChangingTheCurrency: "د اسعارو د بدلولو سره به ټول معلومات په هغه اسعارو بدلون ومومي!",
        register: "راجستر",
        welcomeToBrainbbox: "برین باکس ته ښه راغلاست",
        loginWithGuest: "د میلمه حساب سره ننوتل",
        loginWithGoogle: "د ګوګل سره ننوتل",
        privacyPolicy: "د محرمیت تګلاره",
        welcomeToLogin: "ننوتلو ته ښه راغلاست",
        protectYourData: "خپل معلومات خوندي کړئ، مهرباني وکړئ محلي تصدیق وکاروئ",
        biometricLogin: "بایومیټریک ننوتل",
        alert: "خبرتیا",
        ok: "سمه ده",
        youEnteredInvalidTicket: "تاسو غلط ټکټ داخل کړ",
        noDataFound: "هیڅ معلومات ونه موندل شول",
        noContactFound: "هیڅ اړیکه ونه موندل شوه",
        checkYourTicketHere: "دلته خپل ټکټ وګورئ",
        checkYourTicket: "خپل ټکټ وګورئ",
        check: "کتنه",
        transactionInfo: "د راکړې ورکړې معلومات",
        owner: "مالک",
        name: "نوم",
        type: "ډول",
        info: "معلومات",
        dismiss: "بندول",
        profile: "پيژندنه",
        general: "عمومی",
        report: "راپور",
        dailyReport: "ورځنی راپور",
        balanceSheet: "بیلانس شیټ",
        language: "ژبه",
        opposite: "مخالف",
        doyYouWantToDeleteTransaction: "تاسو ډاډه یاست چې غواړئ دا راکړه ورکړه حذف کړئ؟ دا عمل به ستاسو د نغدو پیسو کتاب اغېزمنه کړي.",
        pleaseSelectCustomer: "مهرباني وکړئ یو پیرودونکی وټاکئ!",
        heDontHaveEnoughCash: "هغه د لیږد لپاره کافي پیسې نلري ایا تاسو پور غواړئ؟",
        balanceSheetCurrency: "د بیلانس شیټ اسعار",
        appLock: " اپلیکیشن قفل",
        updateAvailable: "نوی تازه معلومات شتون لري",
        newVersion: "د اپلیکیشن نوې نسخه شتون لري. مهرباني وکړئ د غوره تجربې لپاره يی تازه کړئ.",
        later: "وروسته",
        updateNow: "همدا اوس تازه کړئ",
        runningBalance: "روان موجودي",
        delete: "ډیلیټ کړئ",
        cancel: "لغوه کړئ",
        appBackup: "د اپلکېشن بیک اپ",
        PickdateToCreateYourAppBackup: "یو نېټه وټاکئ ترڅو د خپلې اپلکېشن بیک اپ جوړ کړئ.",
        yourAppBackupWillStore: "ستاسو د اپ بیک اپ به د ستاسو په موبایل کې 'Download/brainbbox' کې وساتل شي.",
        backupCompleted: "بیک‌اپ په بریالیتوب سره بشپړ شو.",
        CashInSuccessfullyAdded: "نغدې پیسې په بریالیتوب سره داخل شوې.",
        CashOutSuccessfullyAdded: "نغدې پیسې په بریالیتوب سره ووتلې",
        pleaseEnterNumber: "مهرباني وکړئ شمېر داخل کړئ",
        pleaseTryAgain: "مهرباني وکړئ بیا هڅه وکړئ!",
        transper: "انتقال",
        backup: "بیک اپ",
        currencyRate: "د اسعارو نرخ",
        kabul: "کابل",
        kandahar: "کندهار",
        herat: "هرات",
        mazar_i_Sharif: "مزارشریف",
        jalalabad: "جلال‌اباد",
        buy: "پیرودل",
        sell: "پلورل",
        currencyConverter: "د اسعارو بدلون",
        fromCurrency: "له کوم اسعاره",
        toCurrency: "تر کوم اسعاره",
        justnow: "اوس‌مهال",
        minute: "دقیقه",
        ago: "مخکې",
        hour: "ساعت",
        day: "ورځ",
        reminder: "یادونه",
        paymentReminder: "د پیسو یادونه",
        remindeBy: "یادونه شوی لخوا",
        noCurrencyRateFound: "د اسعارو نرخ ونه موندل شو",
        done: "ختم شو",
        deleteAccount: "اکونټ ړنګ کړه",
        MayWeAskWhy: "کولی شو وپوښتو چې ولې روان یی؟",
        send: "ولیږه",
        areYouSureToDeleteAccount: "تاسو باوري یاست چې غواړئ خپل حساب ړنګ کړئ؟",
        sure: "هو",
        deleteAccountMessage: "ستاسو حساب به په ۲۴ ساعتونو کې ړنګ شي.",
        success: "بریا",
        customerSuccessfullyAdded: "پیرودونکی په بریالیتوب سره اضافه شو",
        profileSuccessfullyChanged: "پروفایل په بریالیتوب سره بدل شو",
        privacyPolicy: "د محرمیت تګلاره",
        privacyPolicyMessage: "د دې اپلیکیشن په کارولو سره، تاسو زموږ د محرمیت تګلاره او د خدماتو شرایطو سره موافقه کوئ.",
        agree: "موافق یم",
        disagree: "ناموافق یم",
    },
    pe: {
        isRtl: true,
        hi: "سلام،",
        guest: "میهمان",
        customers: "مشتریان",
        currency: "ارز",
        uploadData: "بارگذاری داده‌ها",
        addCustomer: "اضافه کردن مشتری",
        firstName: "نام",
        lastName: "نام خانوادگی",
        phone: "تلفن",
        email: "ایمیل",
        cashBook: "دفتر حساب",
        show: "نمایش",
        cashIn: "واریز وجه",
        cash: "پول نقد",
        cashOut: "برداشت وجه",
        dateTime: "تاریخ و زمان",
        date: "تاریخ",
        prev: "قبلی",
        next: "بعدی",
        noDataAvailable: "اطلاعاتی موجود نیست",
        customer: "مشتری",
        search: "جستجو",
        customerNotFound: "مشتری پیدا نشد",
        yourDataWillBeAutomatically: "اطلاعات شما ۲۴ ساعت پس از استفاده از حساب میهمان به طور خودکار حذف خواهد شد",
        update: "به‌روزرسانی",
        founder: "بنیانگذار: محمد ناصر یوسفی",
        selfCash: "پول نقد شخصی",
        add: "افزودن",
        edit: "ویرایش",
        amount: "مقدار",
        profit: "سود",
        information: "اطلاعات",
        submit: "ثبت",
        from: "از",
        to: "به",
        share: "اشتراک‌گذاری",
        currency: "ارز",
        byChangingTheCurrency: "با تغییر ارز، تمام اطلاعات به ارز جدید تغییر خواهند کرد!",
        register: "ثبت نام",
        welcomeToBrainbbox: "به برین‌باکس خوش آمدید",
        loginWithGuest: "ورود با حساب میهمان",
        loginWithGoogle: "ورود با گوگل",
        privacyPolicy: "سیاست حفظ حریم خصوصی",
        welcomeToLogin: "به صفحه ورود خوش آمدید",
        protectYourData: "برای حفاظت از اطلاعات خود لطفاً از تأیید محلی استفاده کنید",
        biometricLogin: "ورود بیومتریک",
        alert: "هشدار",
        ok: "باشه",
        youEnteredInvalidTicket: "شما یک بلیط نامعتبر وارد کردید",
        noDataFound: "اطلاعاتی پیدا نشد",
        noContactFound: "تماسی پیدا نشد",
        checkYourTicketHere: "بلیط خود را اینجا بررسی کنید",
        checkYourTicket: "بلیط خود را بررسی کنید",
        check: "بررسی",
        transactionInfo: "اطلاعات تراکنش",
        owner: "مالک",
        name: "نام",
        type: "نوع",
        info: "اطلاعات",
        dismiss: "بستن",
        profile: "نمایه",
        general: "عمومی",
        report: "گزارش",
        dailyReport: "گزارش روزانه",
        balanceSheet: "ترازنامه",
        language: "زبان",
        opposite: "مقابل",
        doyYouWantToDeleteTransaction: "آیا مطمئن هستید که می‌خواهید این تراکنش را حذف کنید؟ این اقدام بر روی دفاتر نقدی شما تأثیر خواهد گذاشت.",
        pleaseSelectCustomer: "لطفا یک مشتری انتخاب کنید!",
        heDontHaveEnoughCash: "او پول نقد کافی برای انتقال ندارد آیا شما بدهی می خواهید؟",
        balanceSheetCurrency: "ارز ترازنامه",
        appLock: "قفل برنامه",
        updateAvailable: "به‌روزرسانی در دسترس است",
        newVersion: "نسخه جدیدی از برنامه موجود است. لطفاً برای تجربه بهتر، به‌روزرسانی کنید.",
        later: "بعداً",
        updateNow: "همین حالا به‌روزرسانی کنید",
        runningBalance: "مانده جاری",
        delete: "حذف",
        cancel: "لغو",
        appBackup: "نسخه پشتیبان برنامه",
        PickdateToCreateYourAppBackup: "یک تاریخ انتخاب کنید تا از برنامه خود نسخه پشتیبان تهیه کنید.",
        yourAppBackupWillStore: "نسخه پشتیبان برنامه شما در دستگاه شما در مسیر 'Download/brainbbox' ذخیره خواهد شد.",
        backupCompleted: "پشتیبان‌گیری با موفقیت انجام شد.",
        CashInSuccessfullyAdded: "ورود وجه با موفقیت انجام شد.",
        CashOutSuccessfullyAdded: "خروج وجه با موفقیت انجام شد",
        pleaseEnterNumber: "لطفاً عدد را وارد کنید",
        pleaseTryAgain: "لطفاً دوباره تلاش کنید!",
        transper: "انتقال",
        backup: "نسخه پشتیبان",
        currencyRate: "نرخ ارز",
        kabul: "کابل",
        kandahar: "قندهار",
        herat: "هرات",
        mazar_i_Sharif: "مزار شریف",
        jalalabad: "جلال‌آباد",
        buy: "خرید",
        sell: "فروش",
        currencyConverter: "مبدل ارز",
        fromCurrency: "از ارز",
        toCurrency: "به ارز",
        justnow: "همین حالا",
        minute: "دقیقه",
        ago: "پیش",
        hour: "ساعت",
        day: "روز",
        reminder: "یادآوری",
        paymentReminder: "یادآوری پرداخت",
        remindeBy: "یادآوری شده توسط",
        noCurrencyRateFound: "نرخ ارز پیدا نشد",
        done: "انجام شد",
        deleteAccount: "حذف حساب",
        MayWeAskWhy: "ممکن است بپرسیم چرا می‌روید؟",
        send: "ارسال",
        areYouSureToDeleteAccount: "آیا مطمئن هستید که می‌خواهید حساب خود را حذف کنید؟",
        sure: "بله",
        deleteAccountMessage: "حساب شما ظرف ۲۴ ساعت حذف خواهد شد.",
        success: "موفقیت",
        customerSuccessfullyAdded: "مشتری با موفقیت اضافه شد",
        profileSuccessfullyChanged: "پروفایل با موفقیت تغییر کرد",
        privacyPolicy: "سیاست حفظ حریم خصوصی",
        privacyPolicyMessage: "با استفاده از این برنامه، شما با سیاست حفظ حریم خصوصی و شرایط خدمات ما موافقت می‌کنید.",
        agree: "موافقم",
        disagree: "مخالفم",
    }
});

export default strings;